### ISSUE TITLE
compilation error (file missing)

### ISSUE THREAD

**Issue by acad2** [HarisPasic/SideChannelAttack#1]
Hi,

Got the following error:
```
receiver.c:11:21: fatal error: ./queue.h: No such file or directory
 #include "./queue.h"
                     ^
compilation terminated.
make: *** [receiver] Error 1
```

Please check.

**Comment by HarisPasic** [comment]
Hi,

I forgot to remove this line. It compiles now. However, I will archive this project and won't update it anymore.

I will just give you some infos : 

It was tested in optimal conditions (=>fresh linux on USB) so I did not have so much noise. 
What you should be modifying is mainly in the file cacheutils.h

#define MIN_CACHE_MISS_CYCLES (210)
#define THRESHOLD 0.02
#define MASK 1<<19
#define REDUNDANCY 8
#define BYTE_SIZE 8
#define MAX_MESSAGE_SIZE 1024
#define MAX_MESSAGE_BITS_SIZE 65536

You play with that until you achieve to send data from the sender to the receiver (e.g. increase the mask and the threshold).

Do not forget to calibrate (MIN_CACHE_MISS_CYCLES ) by following what's written here : https://github.com/clementine-m/cache_template_attacks#step-1-calibration

Good luck,

HP :)
